name: Waka Readme

on:
  schedule:
    - cron: "30 18 * * *" # updates daily at 6:30 PM UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@v1.1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
